print("Word ", '\t\t', "Count")
print('=' * 22)
fo = open('alice.rtf','r').read()
fo = fo.lower()
print('a ', '\t\t', fo.count('a'))
print('abide', '\t\t',fo.count('abide'))
print('able', '\t\t',fo.count('able'))
print('about', '\t\t', fo.count('about'))
print('above', '\t\t', fo.count('above'))
print('absence', '\t', fo.count('absence'))
print('after', '\t\t', fo.count('after'))
print('alice', '\t\t', fo.count('Alice'))
